site_name: 'Python asyncio 资源列表'
site_url: 'http://chenjiandongx/awesome-asyncio-cn/'
site_author: 'chenjiandongx'
repo_name: 'chenjiandongx/awesome-asyncio-cn/'
repo_url: 'https://github.com/chenjiandongx/awesome-asyncio-cn/'
theme: 'material'
extra:
  feature:
    tabs: false
    primary: 'blue'
    accent: 'blue'
  social:
    - type: 'github'
      link: 'https://github.com/chenjiandongx'
pages:
  - "awesome-asyncio-cn": "index.md"
